"""
Utility functions for ShEPhERD inference scaling.

This module provides helper functions for working with ShEPhERD's inference output.
"""

import logging
from copy import deepcopy
from functools import partial
import multiprocessing as mp
from typing import Literal

import numpy as np
from rdkit import Chem, rdBase
from tqdm import tqdm
from rdkit.Chem import AllChem, rdDetermineBonds

from shepherd.generated_sample import GeneratedSample
from shepherd_score.evaluations.evaluate.evals import _clean_dummy_atom_arrays
from shepherd_score.evaluations.utils.convert_data import extract_mol_from_xyz_block
from shepherd_score.conformer_generation import optimize_conformer_with_xtb_from_xyz_block, single_point_xtb_from_xyz

def get_xyz_content(sample):
    """
    Generate XYZ file content string from a ShEPhERD sample.

    Args:
        sample (dict): ShEPhERD output dictionary with x1 containing atoms and positions.

    Returns:
        str: XYZ file content or None if input is invalid.
    """
    if 'x1' not in sample or 'atoms' not in sample['x1'] or 'positions' not in sample['x1']:
        logging.warning("Invalid sample format for XYZ generation")
        return None

    try:
        atoms = sample['x1']['atoms']
        positions = sample['x1']['positions']

        xyz_lines = [f"{len(atoms)}", "Generated by ShEPhERD Inference"]
        for i in range(len(atoms)):
            try:
                atomic_number = int(atoms[i])
                # attempt to get symbol, default to element number if fails
                try:
                    symbol = Chem.Atom(atomic_number).GetSymbol()
                except Exception:
                    symbol = str(atomic_number)
                pos = positions[i]
                xyz_lines.append(f"{symbol} {pos[0]:>15.8f} {pos[1]:>15.8f} {pos[2]:>15.8f}")
            except (ValueError, IndexError) as e:
                logging.warning(f"Skipping atom {i} due to data issue: {e}")
                continue

        xyz_lines[0] = str(len(xyz_lines) - 2)

        return "\n".join(xyz_lines)

    except Exception as e:
        logging.error(f"Error generating XYZ content: {e}")
        return None


def mol_charges_from_sample(
    sample: GeneratedSample | dict,
    solvent: str = 'water',
    xtb_optimize: bool = True,
    charge: int | None = None,
    num_processes: int = 1,
    xtb_timeout: int = 60,
) -> tuple[Chem.Mol | None, np.ndarray | None]:
    """
    Convert a generated sample to an RDKit molecule and calculate xTB charges.

    Uses :func:`create_rdkit_molecule` to infer molecular charge from the XYZ
    coordinates (trying 0, +1, -1, +2, -2) and reject fragments or radicals.

    Always runs a single-point xtb calculation on the initial conformation.
    If ``xtb_optimize=True``, also relaxes with xtb (a few seconds).
    If ``xtb_optimize=False``, returns the unrelaxed mol and its partial charges.

    Arguments
    ---------
    sample: GeneratedSample | dict
        ShEPhERD output dictionary with x1 containing atoms and positions.
    solvent: str
        Implicit solvent for xtb (default: 'water').
    xtb_optimize: bool
        Whether to geometry-optimize with xtb (default: True). ``False`` still
        runs a single-point xtb calculation for partial charges.
    charge: int | None
        Molecular charge used for bond inference and xTB. If omitted, infer
        the charge from the generated coordinates.
    num_processes: int
        Number of CPU cores for xtb (default: 1).
    xtb_timeout: int
        Timeout for xtb (default: 60 seconds).

    Returns
    -------
    tuple[Chem.Mol | None, np.ndarray | None]:
        (mol, xtb partial_charges) for the sample
    """
    mol = create_rdkit_molecule(sample, charge=charge)
    if mol is None:
        return None, None
    if charge is None:
        charge = Chem.GetFormalCharge(mol)
    xyz_block = Chem.MolToXYZBlock(mol)

    # 3. Get xtb energy and charges of initial conformation
    partial_charges = None
    try:
        _, partial_charges = single_point_xtb_from_xyz(xyz_block=xyz_block,
                                                       solvent=solvent,
                                                       charge=charge,
                                                       num_cores=num_processes,
                                                       timeout=xtb_timeout)
        partial_charges = np.array(partial_charges)
    except Exception:
        pass

    if not xtb_optimize:
        return mol, partial_charges

    # 4. Relax structure with xtb
    mol_post_opt, partial_charges_post_opt = None, None
    try:
        xtb_out = optimize_conformer_with_xtb_from_xyz_block(xyz_block,
                                                            solvent=solvent,
                                                            num_cores=num_processes,
                                                            charge=charge,
                                                            timeout=xtb_timeout)
        xyz_block_post_opt, _, partial_charges_post_opt = xtb_out
        partial_charges_post_opt = np.array(partial_charges_post_opt)

        # 5. Check if relaxed_structure is valid
        mol_post_opt = extract_mol_from_xyz_block(
            xyz_block=xyz_block_post_opt,
            charge=charge,
        )
        if _has_radicals(mol_post_opt):
            logging.warning("Rejecting xTB-optimized molecule with radicals")
            return None, None
        return mol_post_opt, partial_charges_post_opt
    except Exception:
        pass

    return mol_post_opt, partial_charges_post_opt


def mol_charges_from_samples(
    samples: list[GeneratedSample],
    num_workers: int = -1,
    solvent: str = 'water',
    xtb_optimize: bool = True,
    charge: int | None = None,
    xtb_timeout: int = 60,
    verbose: bool = False,
) -> list[tuple[Chem.Mol | None, np.ndarray | None]]:
    """
    Convert ShEPhERD outputs to RDKit molecules via xtb (shepherd-score /
    :func:`mol_charges_from_sample` path).

    Arguments
    ---------
    samples: list[GeneratedSample]
        Batch of GeneratedSample objects from inference.
    num_workers: int (default: -1, uses min(num_samples, num_cpus))
        Worker processes for parallel conversion across samples.
    solvent: str (default: 'water')
        Implicit solvent passed to xtb.
    xtb_optimize: bool (default: True)
        Whether to geometry-optimize with xtb (default: True). ``False`` still
        runs a single-point xtb calculation for partial charges.
    charge: int | None
        Molecular charge used for bond inference and xTB. If omitted, infer
        the charge from the generated coordinates.
    xtb_timeout: int (default: 60)
        Per-molecule xtb timeout in seconds.
    verbose: bool (default: False)
        Show a progress bar with tqdm.

    Returns
    -------
    list[tuple[Chem.Mol | None, np.ndarray | None]]:
        List of tuples containing (mol, xtb partial_charges) for each sample.
    """
    worker = partial(
        mol_charges_from_sample,
        solvent=solvent,
        xtb_optimize=xtb_optimize,
        charge=charge,
        xtb_timeout=xtb_timeout,
        num_processes=1, # per worker should stay at 1
    )
    if num_workers <= 0 or num_workers > len(samples):
        num_workers = max(1, min(len(samples), mp.cpu_count()))
    if num_workers > 1:
        blocker = rdBase.BlockLogs()
        try:
            with mp.Pool(processes=num_workers) as pool:
                mol_charges = list(
                    tqdm(
                        pool.imap(worker, samples),
                        total=len(samples),
                        disable=not verbose,
                    )
                )
        finally:
            del blocker
        return mol_charges
    return [
        worker(sample)
        for sample in tqdm(samples, disable=not verbose)
    ]


def create_rdkit_molecule(sample, charge: int | None = None):
    """
    Create an RDKit molecule from ShEPhERD output using its XYZ geometry.

    When ``charge`` is ``None`` (the default), bond determination tries 0,
    +1, -1, +2, and -2 in that order. Supplying a charge restricts bond
    determination to that charge, without optimizing the geometry.

    Arguments
    ---------
    sample : dict
        ShEPhERD output dictionary with x1 containing atoms and positions.
    charge : int, optional
        Fixed molecular charge for bond determination. If omitted, infer a
        workable charge by trying 0, +1, -1, +2, and -2.

    Returns
    -------
    Chem.Mol: RDKit molecule object or None if conversion fails.
    """
    if 'x1' not in sample:
        logging.warning("No atom data (x1) found in sample")
        return None

    try:
        # extract atoms and their positions from x1
        atoms, positions = _clean_dummy_atom_arrays(sample['x1']['atoms'], sample['x1']['positions'])

        # create XYZ format string
        xyz = f'{len(atoms)}\n\n'
        for a in range(len(atoms)):
            atomic_number = int(atoms[a])
            position = positions[a]
            symbol = Chem.Atom(atomic_number).GetSymbol()
            xyz += f'{symbol} {position[0]:.3f} {position[1]:.3f} {position[2]:.3f}\n'

        # create molecule from XYZ block
        mol = Chem.MolFromXYZBlock(xyz)
        if mol is None:
            logging.warning("Failed to create molecule from XYZ block")
            return None

        mol_final, _ = _determine_bonds_and_validate(mol, charge=charge)
        return mol_final

    except Exception as e:
        logging.warning(f"Error creating molecule: {e}")
        return None


def _determine_bonds_and_validate(mol, charge: int | None = None):
    """
    Determine and validate bonds for an RDKit molecule from XYZ coordinates.

    If ``charge`` is omitted, try the common charge states used by the general
    inference converter. If supplied, try only that fixed charge.

    Returns
    -------
    tuple[Chem.Mol | None, str | None]:
        (mol_with_bonds, smiles) or (None, None) if it fails.
    """
    mol_final = None
    charges_to_try = [0, 1, -1, 2, -2] if charge is None else [charge]
    for candidate_charge in charges_to_try:
        mol_copy = deepcopy(mol)
        try:
            rdDetermineBonds.DetermineBonds(
                mol_copy, charge=candidate_charge, embedChiral=True
            )
            logging.debug(
                "Bond determination successful with charge %s", candidate_charge
            )
            mol_final = mol_copy
            break
        except Exception as e:
            logging.debug(f"Bond determination failed with charge {charge}: {e}")
            continue

    if mol_final is None:
        return None, None

    # validate molecule
    try:
        if _has_radicals(mol_final):
            logging.warning("Rejecting molecule with radicals")
            return None, None
        mol_final.UpdatePropertyCache()
        Chem.GetSymmSSSR(mol_final)
    except Exception as e:
        logging.warning(f"Molecule validation failed: {e}")
        return None, None

    try:
        smiles = Chem.MolToSmiles(mol_final)
    except Exception as e:
        logging.warning(f"SMILES generation failed: {e}")
        return None, None

    if '.' in smiles:
        logging.warning("Molecule is a fragment")
        return None, None

    return mol_final, smiles


def _has_radicals(mol: Chem.Mol | None) -> bool:
    """Return whether ``mol`` contains any radical electrons."""
    return mol is not None and any(
        atom.GetNumRadicalElectrons() > 0 for atom in mol.GetAtoms()
    )


def _ff_relax_mol(mol, max_iters=500):
    """
    Relax a molecule with MMFF94 (falling back to UFF) to fix strained geometries.
    Returns a new XYZ block string, or None if relaxation fails.
    """
    mol_h = Chem.AddHs(mol, addCoords=True)
    try:
        # try MMFF94 first
        ff_props = AllChem.MMFFGetMoleculeProperties(mol_h)
        if ff_props is not None:
            ff = AllChem.MMFFGetMoleculeForceField(mol_h, ff_props)
            if ff is not None:
                ff.Minimize(maxIts=max_iters)
                logging.info("MMFF94 force field relaxation succeeded")
            else:
                raise RuntimeError("MMFF force field setup failed")
        else:
            raise RuntimeError("MMFF properties unavailable")
    except Exception:
        # fall back to UFF
        try:
            ff = AllChem.UFFGetMoleculeForceField(mol_h)
            if ff is not None:
                ff.Minimize(maxIts=max_iters)
                logging.info("UFF force field relaxation succeeded")
            else:
                logging.warning("UFF force field setup failed")
                return None
        except Exception as e:
            logging.warning(f"Force field relaxation failed entirely: {e}")
            return None

    # remove Hs and convert back to XYZ block
    mol_noh = Chem.RemoveHs(mol_h)
    xyz_block = Chem.MolToXYZBlock(mol_noh)
    return xyz_block


def create_rdkit_molecule_xtb_optimized(
    sample,
    solvent:str = 'water',
    num_processes:int = 1,
    charge:int = 0,
):
    """
    Create an RDKit molecule from ShEPhERD output with xtb at a fixed charge.

    Unlike :func:`mol_charges_from_sample`, xtb is run at ``charge``
    (default 0) rather than inferring charge from the xyz. If xtb fails
    (e.g. strained geometry):
      1. Determine bonds from the raw coordinates
      2. Pre-relax with MMFF94/UFF force field to fix clashes
      3. Retry xtb on the relaxed geometry
      4. If xtb still fails, use the force-field-relaxed geometry

    Arguments
    ---------
    sample (dict): ShEPhERD output dictionary with x1 containing atoms and positions.
    solvent: str
        Implicit solvent for xtb (default: 'water').
    num_processes: int
        Number of CPU cores for xtb (default: 1).
    charge: int
        Molecular charge (default: 0).

    Returns
    -------
    Chem.Mol: RDKit molecule object or None if conversion fails.
    """
    if 'x1' not in sample:
        logging.warning("No atom data (x1) found in sample")
        return None

    try:
        # extract atoms and their positions from x1
        atoms, positions = _clean_dummy_atom_arrays(sample['x1']['atoms'], sample['x1']['positions'])

        # create XYZ format string
        xyz = f'{len(atoms)}\n\n'
        for a in range(len(atoms)):
            atomic_number = int(atoms[a])
            position = positions[a]
            symbol = Chem.Atom(atomic_number).GetSymbol()
            xyz += f'{symbol} {position[0]:.3f} {position[1]:.3f} {position[2]:.3f}\n'

        # --- Step 1: try xtb directly on raw coordinates ---
        xtb_succeeded = False
        # print("Optimizing conformer with xtb...")
        try:
            xyz_block_post_opt, _, _ = optimize_conformer_with_xtb_from_xyz_block(
                xyz, solvent=solvent, num_cores=num_processes,
                charge=charge)
            if xyz_block_post_opt is not None:
                xtb_succeeded = True
        except Exception as e:
            logging.warning(f"xtb optimization failed on raw coordinates: {e}")
            xyz_block_post_opt = None

        # --- Step 2: if xtb failed, pre-relax with force field and retry ---
        if not xtb_succeeded:
            logging.info("Attempting force field pre-relaxation before retrying xtb...")

            # determine bonds from raw XYZ so force field has connectivity
            raw_mol = Chem.MolFromXYZBlock(xyz)
            if raw_mol is None:
                logging.warning("Failed to create molecule from raw XYZ block")
                return None

            mol_with_bonds, _ = _determine_bonds_and_validate(raw_mol, charge=charge)
            if mol_with_bonds is None:
                logging.warning("Could not determine bonds from raw coordinates")
                return None

            relaxed_xyz = _ff_relax_mol(mol_with_bonds)
            if relaxed_xyz is not None:
                # retry xtb on force-field-relaxed geometry
                try:
                    print("Retrying xtb on force-field-relaxed geometry...")
                    xyz_block_post_opt, _, _ = optimize_conformer_with_xtb_from_xyz_block(
                        relaxed_xyz, solvent=solvent, num_cores=num_processes,
                        charge=charge)
                    if xyz_block_post_opt is not None:
                        xtb_succeeded = True
                except Exception as e:
                    logging.warning(f"xtb retry also failed: {e}")
                    xyz_block_post_opt = None

                # if xtb still fails, use the force-field-relaxed geometry
                if not xtb_succeeded:
                    logging.warning("Using force-field-relaxed coordinates (no xtb)")
                    xyz_block_post_opt = relaxed_xyz
            else:
                # force field relaxation failed too, use raw coordinates
                logging.warning("Force field relaxation failed, using raw coordinates")
                xyz_block_post_opt = xyz

        # --- Step 3: build final molecule from best available coordinates ---
        mol = Chem.MolFromXYZBlock(xyz_block_post_opt)
        if mol is None:
            logging.warning("Failed to create molecule from XYZ block")
            return None

        mol_final, smiles = _determine_bonds_and_validate(mol, charge=charge)
        if mol_final is None:
            logging.warning("Bond determination / validation failed")
            return None

        logging.debug(f"Generated SMILES: {smiles}")
        return mol_final

    except Exception as e:
        logging.warning(f"Error creating molecule: {e}")
        return None


def create_smiles_from_samples_xtb_optimized(
    samples,
    solvent: str = 'water',
    num_processes: int = 2,
    num_workers: int = 2,
    mp_context: Literal['spawn', 'forkserver'] = 'spawn'):
    from shepherd_score.evaluations.evaluate import UnconditionalEvalPipeline

    generated_mols = []
    for gen_struct in samples:
        atoms, positions = _clean_dummy_atom_arrays(gen_struct['x1']['atoms'], gen_struct['x1']['positions'])
        generated_mols.append((atoms, positions))

    uncond_pipe = UnconditionalEvalPipeline(generated_mols=generated_mols, solvent=solvent)
    uncond_pipe.evaluate(verbose=True, num_processes=num_processes, num_workers=num_workers, mp_context=mp_context)

    mols = [Chem.MolFromMolBlock(molblock, removeHs=False) if molblock is not None else None for molblock in uncond_pipe.molblocks_post_opt if molblock is not None]
    smiles = [Chem.MolToSmiles(mol, allHsExplicit=True) if mol is not None else None for mol in mols]
    return smiles


def create_mols_from_samples_xtb_optimized(
    samples,
    solvent: str = 'water',
    num_processes: int = 2,
    num_workers: int = 2,
    mp_context: Literal['spawn', 'forkserver'] = 'spawn'):
    from shepherd_score.evaluations.evaluate import UnconditionalEvalPipeline

    generated_mols = []
    for gen_struct in samples:
        atoms, positions = _clean_dummy_atom_arrays(gen_struct['x1']['atoms'], gen_struct['x1']['positions'])
        generated_mols.append((atoms, positions))

    uncond_pipe = UnconditionalEvalPipeline(generated_mols=generated_mols, solvent=solvent)
    uncond_pipe.evaluate(verbose=True, num_processes=num_processes, num_workers=num_workers, mp_context=mp_context)

    mols = [Chem.MolFromMolBlock(molblock, removeHs=False) if molblock is not None else None for molblock in uncond_pipe.molblocks_post_opt if molblock is not None]
    return mols

def _remove_overlaps(
    positions: np.ndarray,
    atoms: np.ndarray,
    inpainted_atom_positions: np.ndarray,
    cutoff: float = 0.7,
    keep_dummy_atoms: bool = True,
    verbose: bool = False
) -> tuple[np.ndarray, np.ndarray]:
    """
    Remove atoms that overlap with inpainted atoms.
    Assumes `inpainted_atom_positions` are the first `num_inpainted_atoms` atoms in `positions`.
    """
    num_total_atoms = len(positions)
    num_inpainted_atoms = len(inpainted_atom_positions)
    diffused_atom_pos = positions[num_inpainted_atoms:]
    pairwise_diff = diffused_atom_pos[:, None] - inpainted_atom_positions[None, :]
    rmse_atoms = np.sqrt(np.mean(np.square(pairwise_diff), axis=2))
    overlap_inds = np.where(np.any(np.isclose(rmse_atoms, np.zeros(rmse_atoms.shape), atol=cutoff), axis=1))[0]
    if verbose:
        print(f'Removing inds: {overlap_inds + num_inpainted_atoms}')
    if keep_dummy_atoms:
        inds_to_keep = np.array([i for i in range(num_total_atoms) if i not in overlap_inds + num_inpainted_atoms or atoms[i] == 0])
    else:
        inds_to_keep = np.array([i for i in range(num_total_atoms) if i not in overlap_inds + num_inpainted_atoms])
    return positions[inds_to_keep], atoms[inds_to_keep]


def remove_overlaps(generated_sample: dict,
                    inpainted_atom_positions: np.ndarray,
                    cutoff: float = 0.7,
                    keep_dummy_atoms: bool = True,
                    verbose: bool = False) -> dict:
    """
    Remove atoms that overlap with inpainted atoms.
    Assumes `inpainted_atom_positions` are the first `num_inpainted_atoms` atoms in `generated_sample['x1']['positions']`.

    Arguments
    ---------
    generated_sample: dict
        ShEPhERD output dictionary with x1 containing atoms and positions.
    inpainted_atom_positions: np.ndarray
        Array of inpainted atom positions.
    cutoff: float (default: 0.7)
        Cutoff distance (RMSD) for overlap.
    keep_dummy_atoms: bool (default: True)
        Whether to keep dummy atoms.
    verbose: bool (default: False)
        Whether to print verbose output.

    Returns
    -------
    dict:
        ShEPhERD output dictionary where atoms that overlap with inpainted atoms are removed.
        Note that this does not alter the bond information.
    """
    new_positions, new_atoms = _remove_overlaps(
        positions=generated_sample['x1']['positions'],
        atoms=generated_sample['x1']['atoms'],
        inpainted_atom_positions=inpainted_atom_positions,
        cutoff=cutoff,
        keep_dummy_atoms=keep_dummy_atoms,
        verbose=verbose
    )
    out = deepcopy(generated_sample)
    out['x1']['positions'] = new_positions
    out['x1']['atoms'] = new_atoms
    return out


def remove_side_groups_with_geometry(mol: Chem.Mol, atoms_to_remove: list[int]) -> Chem.Mol:
    """
    Remove atoms in `atoms_to_remove` and add hydrogens using RDKit's AddHs(addCoords=True)
    to preserve 3D geometry. Returns a new RDKit molecule.

    Arguments
    ---------
    mol: Chem.Mol
        RDKit molecule with conformer
    atoms_to_remove: list[int]
        List of atom indices to delete

    Returns
    -------
    Chem.Mol:
        RDKit molecule with hydrogens added and side groups removed.
    """
    conf = mol.GetConformer()
    pos = conf.GetPositions()

    atoms_to_keep = sorted(set(range(mol.GetNumAtoms())) - set(atoms_to_remove))

    # old_to_new = {old_idx: new_idx for new_idx, old_idx in enumerate(atoms_to_keep)}

    rw_mol = Chem.RWMol() # editable mol
    atom_map = {}

    for idx in atoms_to_keep:
        atom = mol.GetAtomWithIdx(idx)
        new_atom = Chem.Atom(atom.GetAtomicNum())
        new_idx = rw_mol.AddAtom(new_atom)
        atom_map[idx] = new_idx

    for bond in mol.GetBonds():
        a1, a2 = bond.GetBeginAtomIdx(), bond.GetEndAtomIdx()
        if a1 in atoms_to_keep and a2 in atoms_to_keep:
            rw_mol.AddBond(atom_map[a1], atom_map[a2], bond.GetBondType())

    new_mol = rw_mol.GetMol()
    new_conf = Chem.Conformer(len(atoms_to_keep))

    for new_idx, old_idx in enumerate(atoms_to_keep):
        x, y, z = pos[old_idx]
        new_conf.SetAtomPosition(new_idx, (x, y, z))

    new_mol.RemoveAllConformers()
    new_mol.AddConformer(new_conf, assignId=True)

    Chem.SanitizeMol(new_mol)
    mol_with_H = Chem.AddHs(new_mol, addCoords=True)

    return mol_with_H
