"""
GeneratedSample: a single molecule produced by shepherd.inference.sampler.generate().
"""
from __future__ import annotations
from typing import TYPE_CHECKING

import numpy as np

if TYPE_CHECKING:
    from rdkit import Chem
    from shepherd.interaction_profile import InteractionProfile

class GeneratedSample(dict):
    """One sample generated by ShEPhERD."""

    # x1 (atoms)
    @property
    def atoms(self) -> np.ndarray:
        return self['x1']['atoms']

    @property
    def positions(self) -> np.ndarray:
        return self['x1']['positions']

    @property
    def bonds(self) -> np.ndarray:
        return self['x1']['bonds']

    @property
    def formal_charges(self) -> np.ndarray:
        return self['x1']['formal_charges']

    # x2 / x3 (surface + electrostatics)
    @property
    def surface(self) -> np.ndarray:
        return self['x3']['positions']

    @property
    def electrostatics(self) -> np.ndarray:
        return self['x3']['charges']

    # x4 (pharmacophores)
    @property
    def pharm_types(self) -> np.ndarray:
        return self['x4']['types']

    @property
    def pharm_positions(self) -> np.ndarray:
        return self['x4']['positions']

    @property
    def pharm_directions(self) -> np.ndarray:
        return self['x4']['directions']

    # conversions
    def to_mol_charges(
        self,
        xtb_optimize: bool = True,
        solvent: str = 'water',
        charge: int | None = None,
        num_processes: int = 1,
        xtb_timeout: int = 60,
    ) -> tuple['Chem.Mol', np.ndarray]:
        """Convert to mol and compute xTB partial charges. Optionally, relax.

        Arguments
        ----------
        xtb_optimize : bool (default: True)
            Whether to optimize the molecule using xTB.
        solvent : str (default: 'water')
            The solvent to use for the xTB optimization.
        charge : int | None (default: None)
            The charge to assign to the molecule. The charge will be inferred from the molecule
            unless a charge is specified.
        num_processes : int (default: 1)
            The number of processes to use for the xTB optimization.
        xtb_timeout : int (default: 60)
            The timeout for the xTB optimization. Increase if they time-out, frequently.

        Returns
        -------
        tuple[Chem.Mol, np.ndarray]
        """
        from shepherd.extract import mol_charges_from_sample
        return mol_charges_from_sample(
            self, charge=charge, xtb_optimize=xtb_optimize, solvent=solvent,
            num_processes=num_processes, xtb_timeout=xtb_timeout
        )

    def remove_overlaps(self, inpainted_atom_positions: np.ndarray, **kwargs) -> 'GeneratedSample':
        """Remove generated atoms that overlap with fixed atoms during scaffold conditioning/inpainting.

        Example:
        gen_sample = GeneratedSample(...)
        >>> gen_sample_no_overlaps = gen_sample.remove_overlaps(ConditionAtoms.pos)
        """
        from shepherd.extract import remove_overlaps
        return GeneratedSample(remove_overlaps(self, inpainted_atom_positions, **kwargs))

    def to_interaction_profile(
        self,
        center: bool = True,
        xtb_optimize: bool = True,
        solvent: str = 'water',
        charge: int | None = None,
        neutralize_esp: bool = False,
        num_processes: int = 1,
        xtb_timeout: int = 60,
    ) -> 'InteractionProfile':
        """Re-extract this sample's interaction profile.

        Arguments
        ----------
        center : bool (default: True)
            Whether to center the molecule.
        xtb_optimize : bool (default: True)
            Whether to optimize the molecule using xTB.
        solvent : str (default: 'water')
            The solvent to use for the xTB optimization.
        charge : int | None (default: None)
            The charge to assign to the molecule. The charge will be inferred from the molecule
            unless a charge is specified.
        neutralize_esp : bool (default: False)
            Whether to neutralize the electrostatic potential.
        num_processes : int (default: 1)
            The number of processes to use for the xTB optimization.
        xtb_timeout : int (default: 60)
            The timeout for the xTB optimization. Increase if they time-out, frequently.

        Returns
        -------
        InteractionProfile
        """
        from shepherd.interaction_profile import InteractionProfile
        return InteractionProfile.from_generated_sample(
            self,
            center=center,
            xtb_optimize=xtb_optimize,
            conversion='inferred',
            solvent=solvent,
            charge=charge,
            num_processes=num_processes,
            xtb_timeout=xtb_timeout,
            neutralize_esp=neutralize_esp,
        )
